/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package indizado_prueba;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;

/**
 *
 * @author kevda
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresar = new javax.swing.JButton();
        txtLlave = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLlave, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIngresar)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(txtLlave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(251, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void escribirPrimero(int n)
    {
        File Archivo = new File("MEIA/indice.txt");
        
        if(Archivo.exists()!=true)
        {
            try
            {
                Archivo.createNewFile();
                try (FileWriter Escribir = new FileWriter(Archivo,true)) {
                    Escribir.write((n +"|xyz|" + txtLlave.getText() + "|" + "null") + System.getProperty( "line.separator" ));
                    Escribir.close();                    
                }
           
            }
            catch(IOException ex)
            {

            }            
        }
        else
        {   
           //File Archivo = new File(strPath);
            try
            {
                FileWriter Escribir = new FileWriter(Archivo,true);
                BufferedWriter bw = new BufferedWriter(Escribir);
                bw.write((n +"|bloque|" + txtLlave.getText() + "|" + "null")+ System.getProperty( "line.separator" ));
                bw.close();
                Escribir.close();
                

            }
            catch(IOException ex)
            {

            } 
        }
    }
    public void buscar(int inicio,String registro)
    {
        File pathFolderMEIA = new File("MEIA");
        String strPath = pathFolderMEIA + "/indice.txt";
        String[] strRegistro = registro.split("\\|");
        try
        {
        RandomAccessFile filetoUse = new RandomAccessFile(strPath, "rw");
 
        while(filetoUse!= null)
        {
            String linea = filetoUse.readLine();
            String[] str = linea.split("\\|");
            String lineaCambiada ="";
            String lineaCambiadaRegistro ="";
 
                if(Integer.parseInt(str[0]) == inicio)
                {
                    if(str[3].equals("vacio"))
                    {
                         for(int j = 0; j<4;j++)
                        {
                            if(j == 0)
                            {
                                lineaCambiada += str[j];
                                lineaCambiadaRegistro += strRegistro[j];
                            }
                            else
                            {
                                if(j == 3)
                                {
                                        lineaCambiada += "|" + str[j].replace(str[j],strRegistro[0]);
                                        lineaCambiadaRegistro += "|" + strRegistro[j].replace(strRegistro[j],"vacio");
                                        
                                }
                                else 
                                {
                                    lineaCambiada += "|" + str[j];
                                    lineaCambiadaRegistro += "|" + strRegistro[j];
                                }
                            }
                        }
                        long suma = linea.length();
                        System.out.println("esto es el largo de la linea" + suma);
                        long position = filetoUse.getFilePointer();   
                        System.out.println("esto devuelve el filepointer" + position);
                        System.out.println("esto devuelve al final: " + (filetoUse.getFilePointer()-(suma+2)));
                        filetoUse.seek(filetoUse.getFilePointer()-(suma+2));
                        System.out.println("esto es linea cambiada: "+(lineaCambiada)+System.getProperty("line.separator"));
                        filetoUse.write((lineaCambiada + System.getProperty( "line.separator" )).getBytes());   
                    }                 
                }   
                else if(strRegistro[2].compareTo(str[2]) >= 0)
                {
                    
                    for(int j = 0; j<4;j++)
                        {
                            if(j == 0)
                            {
                                lineaCambiada += str[j];
                                lineaCambiadaRegistro += strRegistro[j];
                            }
                            else
                            {
                                if(j == 3)
                                {
                                        String aux = str[j];
                                        lineaCambiada += "|" + str[j].replace(str[j],strRegistro[0]);
                                        lineaCambiadaRegistro += "|" + strRegistro[j].replace(strRegistro[j], aux);                                        
                                        buscar(Integer.parseInt(strRegistro[j]),lineaCambiadaRegistro);
                                        
                                }
                                else 
                                {
                                    lineaCambiada += "|" + str[j];
                                    lineaCambiadaRegistro += "|" + strRegistro[j];
                                }
                            }
                        }
                }
                else if(strRegistro[2].compareTo(str[2])< 0)
                {
                    buscar(Integer.parseInt(str[3]),registro);
                }
        }
        filetoUse.close();
        }
        catch(IOException e){
            e.printStackTrace();
        }
    }
    int cont = 1;
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        if(cont == 1)
        {
            escribirPrimero(cont);
        }
        else
        {
            String cadena = cont +"|xy|" + txtLlave.getText() + "|" + "vacio"; 
            buscar(1,cadena);
        }
        cont++;
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look an0.
        
        33
        d feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JTextField txtLlave;
    // End of variables declaration//GEN-END:variables
}
